// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0dJeKqT1grCcpancRo_buKOQzvJGMUNY',
    appId: '1:1097846532237:web:78fcd7e8b27f76cb151ac4',
    messagingSenderId: '1097846532237',
    projectId: 'projeto-carteira',
    authDomain: 'projeto-carteira.firebaseapp.com',
    storageBucket: 'projeto-carteira.appspot.com',
    measurementId: 'G-5WS383T2ZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhQHs1sFALq5pnkrPWXCfYMT_Xjj3F1uU',
    appId: '1:1097846532237:android:4b63fa954e574c4f151ac4',
    messagingSenderId: '1097846532237',
    projectId: 'projeto-carteira',
    storageBucket: 'projeto-carteira.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfqXYHKLxeS_FIr01RU-J1mMblXW6QHF0',
    appId: '1:1097846532237:ios:c586b01ac04be38d151ac4',
    messagingSenderId: '1097846532237',
    projectId: 'projeto-carteira',
    storageBucket: 'projeto-carteira.appspot.com',
    iosClientId:
        '1097846532237-qn4pr4fp8do68t1a094khbn895i2vdjb.apps.googleusercontent.com',
    iosBundleId: 'com.wols.projetoCarteira',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfqXYHKLxeS_FIr01RU-J1mMblXW6QHF0',
    appId: '1:1097846532237:ios:c586b01ac04be38d151ac4',
    messagingSenderId: '1097846532237',
    projectId: 'projeto-carteira',
    storageBucket: 'projeto-carteira.appspot.com',
    iosClientId:
        '1097846532237-qn4pr4fp8do68t1a094khbn895i2vdjb.apps.googleusercontent.com',
    iosBundleId: 'com.wols.projetoCarteira',
  );
}
